import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,Check,ChevronDown,Clock3,HeartPulse,MapPin,Menu,MessageCircle,Phone,Search,ShieldCheck,ShoppingBag,Stethoscope,X,Upload,Navigation,Plus} from 'lucide-react';
import './styles.css';

const PHONE='+92 300 1234567', WHATS='923001234567';
const cats=[['Prescription Medicines','Rx'],['Vitamins & Wellness','VW'],['Mother & Baby','MB'],['Personal Care','PC'],['Health Devices','HD'],['First Aid','FA']];
const products=[['Everyday Pain Relief','OTC essentials','From Rs. 120','pain'],['Daily Wellness','Vitamins & supplements','From Rs. 350','well'],['Baby Care Essentials','Mother & baby','From Rs. 250','baby'],['Home First Aid','First-aid supplies','From Rs. 180','aid']];
const faqs=[['Can I send a prescription on WhatsApp?','Yes. For the demo, customers can use the medicine request form or WhatsApp. A production version can connect requests directly to your team.'],['Can I check medicine availability?','Send the medicine name, strength and quantity. Your team can confirm availability before the customer visits.'],['Do you offer delivery?','Delivery can be enabled based on your service area and operating policy. This demo keeps that setting flexible.'],['Can this become a full online pharmacy?','Yes. The structure is ready to expand into inventory, customer accounts, order tracking and online payments.']];

function Logo(){return <div className="logo"><span className="logoMark"><Plus size={20}/></span><span><b>MediCare</b><small>PHARMACY</small></span></div>}
function App(){
 const [menu,setMenu]=useState(false),[modal,setModal]=useState(false),[sent,setSent]=useState(false),[query,setQuery]=useState(''),[openFaq,setOpenFaq]=useState(0);
 const filtered=products.filter(p=>p.join(' ').toLowerCase().includes(query.toLowerCase()));
 const nav=['Services','Shop','About','Contact'];
 const close=()=>{setModal(false);setTimeout(()=>setSent(false),300)};
 return <div>
  <div className="announcement"><div>Serving <b>Mandi Bahauddin</b> & nearby areas</div><div className="announceRight"><span><Clock3 size={14}/> Open today · 9 AM — 11 PM</span><a href={'tel:'+PHONE}><Phone size={14}/>{PHONE}</a></div></div>
  <header><div className="navWrap"><a className="brand" href="#home"><Logo/></a><nav>{nav.map(n=><a key={n} href={'#'+n.toLowerCase()}>{n}</a>)}</nav><a className="navWhats" href={'https://wa.me/'+WHATS} target="_blank"><MessageCircle size={17}/> WhatsApp</a><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="mobileNav">{nav.map(n=><a onClick={()=>setMenu(false)} key={n} href={'#'+n.toLowerCase()}>{n}</a>)}<a href={'https://wa.me/'+WHATS}>WhatsApp</a></div>}</header>
  <main>
   <section id="home" className="hero"><div className="heroCopy"><div className="eyebrow"><span></span> YOUR LOCAL HEALTHCARE PARTNER</div><h1>Healthcare that feels <em>closer.</em></h1><p className="heroLead">A modern pharmacy experience built around the people of Mandi Bahauddin — clear, convenient and easy to reach.</p><div className="heroBtns"><button className="primary" onClick={()=>setModal(true)}>Request a medicine <ArrowUpRight size={18}/></button><a className="secondary" href={'https://wa.me/'+WHATS} target="_blank"><MessageCircle size={18}/> Chat on WhatsApp</a></div><div className="trust"><span><ShieldCheck/> Genuine products</span><span><HeartPulse/> Local service</span><span><LockIcon/> Private requests</span></div></div>
    <div className="heroVisual"><div className="halo h1"></div><div className="halo h2"></div><div className="heroPanel"><div className="panelTop"><span className="live"><i></i> OPEN NOW</span><span>MB · PK</span></div><div className="crossBig"><Plus/></div><div className="panelTitle">Your health,<br/><strong>handled with care.</strong></div><div className="panelLine"></div><div className="panelBottom"><span><MapPin/> Mandi Bahauddin</span><span>09:00—23:00</span></div></div><div className="floatCard request"><div className="floatIcon"><MessageCircle/></div><div><b>Need a medicine?</b><small>Send a request in seconds</small></div><ArrowUpRight size={17}/></div><div className="floatCard rating"><strong>4.9</strong><span>★★★★★</span><small>Customer-first service</small></div></div></section>
   <div className="quick"><a href="#services"><span>01</span><b>Explore services</b><ArrowUpRight/></a><a href="#shop"><span>02</span><b>Browse categories</b><ArrowUpRight/></a><a href="#contact"><span>03</span><b>Get directions</b><ArrowUpRight/></a></div>

   <section id="services" className="section services"><div className="sectionHead"><div><div className="eyebrow">DESIGNED FOR REAL LIFE</div><h2>Everything you need,<br/><em>without the hassle.</em></h2></div><p>From a quick prescription request to finding the right everyday essentials, every interaction is designed to be simple.</p></div><div className="serviceGrid">{[['01','Prescription requests','Send medicine details without making an extra trip.','request'],['02','WhatsApp support','Ask a question or confirm availability from your phone.','chat'],['03','Easy directions','Find the pharmacy quickly when you need it most.','map'],['04','Product discovery','Browse common health categories before you visit.','shop']].map(([n,t,d,i])=><div className="service" key={t}><span className="serviceNo">{n}</span><div className="serviceIcon">{i==='request'?<Upload/>:i==='chat'?<MessageCircle/>:i==='map'?<Navigation/>:<ShoppingBag/>}</div><h3>{t}</h3><p>{d}</p><a href={i==='map'?'#contact':i==='shop'?'#shop':'#home'}>Learn more <ArrowUpRight size={15}/></a></div>)}</div></section>

   <section id="shop" className="section shop"><div className="shopTop"><div><div className="eyebrow">SHOP · DISCOVER · REQUEST</div><h2>A clearer way to<br/><em>find what you need.</em></h2></div><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search demo products..."/></div></div><div className="catGrid">{cats.map(([name,abbr])=><button key={name} onClick={()=>setQuery(name.split(' ')[0])}><span>{abbr}</span><b>{name}</b><ArrowUpRight/></button>)}</div><div className="productGrid">{filtered.map(([title,sub,price,type])=><div className="product" key={title}><div className={'productArt '+type}><div className="bottle"><span>+</span></div></div><div className="productInfo"><small>{sub}</small><h3>{title}</h3><div><b>{price}</b><button onClick={()=>setModal(true)}>Request <ArrowUpRight size={14}/></button></div></div></div>)}</div><div className="requestBanner"><div><span className="bannerTag">CAN'T FIND IT?</span><h3>Tell us what you're looking for.</h3><p>Send the name, strength and quantity. We’ll take it from there.</p></div><button className="primary" onClick={()=>setModal(true)}>Make a request <ArrowUpRight/></button></div></section>

   <section id="about" className="section about"><div className="aboutVisual"><div className="window"><div className="windowSign"><Plus/><span>MEDICARE</span></div><div className="shelf"><i></i><i></i><i></i><i></i></div><div className="counter"><span></span><span></span><span></span></div></div><div className="badge"><Check/> Customer-first</div></div><div className="aboutCopy"><div className="eyebrow">WHY THIS EXPERIENCE WORKS</div><h2>Modern service.<br/><em>Local feel.</em></h2><p>This isn’t just a brochure website. It gives a local pharmacy a polished digital front door — one that answers common questions, makes contact effortless and can grow with the business.</p><div className="points"><div><b>Clear information</b><span>Hours, location, services and contact details stay easy to find.</span></div><div><b>Built for mobile</b><span>Fast customer actions are always one tap away.</span></div><div><b>Ready to grow</b><span>Inventory, delivery and online ordering can be added later.</span></div></div></div></section>
   <section className="numbers"><div><b>01</b><span>Local-first design</span></div><div><b>02</b><span>Mobile customer flows</span></div><div><b>03</b><span>Request-ready structure</span></div><div><b>04</b><span>Expandable foundation</span></div></section>

   <section className="section faq"><div className="faqHead"><div className="eyebrow">COMMON QUESTIONS</div><h2>Good to know.</h2><p>Short answers for the things customers usually want to know before visiting.</p></div><div className="faqList">{faqs.map(([q,a],i)=><div className={'faqItem '+(openFaq===i?'active':'')} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}><span>{q}</span>{openFaq===i?<X/>:<ChevronDown/>}</button>{openFaq===i&&<p>{a}</p>}</div>)}</div></section>

   <section id="contact" className="section contact"><div className="contactCopy"><div className="eyebrow">COME BY · CALL · MESSAGE</div><h2>Here when<br/><em>you need us.</em></h2><p>Keep the essentials visible. Customers can call, message or get directions without hunting through a page.</p><div className="contactRows"><a href={'tel:'+PHONE}><span><Phone/></span><div><small>CALL</small><b>{PHONE}</b></div><ArrowUpRight/></a><a href={'https://wa.me/'+WHATS} target="_blank"><span><MessageCircle/></span><div><small>WHATSAPP</small><b>Chat with our team</b></div><ArrowUpRight/></a><div><span><MapPin/></span><div><small>VISIT</small><b>Main Bazaar, Mandi Bahauddin</b></div></div><div><span><Clock3/></span><div><small>DEMO HOURS</small><b>Every day · 9 AM — 11 PM</b></div></div></div></div><div className="mapCard"><div className="mapGrid"></div><div className="mapRoad r1"></div><div className="mapRoad r2"></div><div className="mapPin"><MapPin/></div><div className="mapLabel"><b>MediCare Pharmacy</b><span>Main Bazaar</span></div><a className="directions" href="https://www.google.com/maps/search/?api=1&query=Main+Bazaar+Mandi+Bahauddin" target="_blank">Open in Google Maps <ArrowUpRight/></a></div></section>
  </main>
  <footer><Logo/><span>© 2026 MediCare Pharmacy. Demo website.</span><a href="#home">Back to top ↑</a></footer>
  {modal&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal">{!sent?<><button className="close" onClick={close}><X/></button><div className="eyebrow">QUICK REQUEST</div><h2>What do you need?</h2><p>Send the details below. This demo form is ready to connect to WhatsApp, email or a backend.</p><label>Medicine / product<input placeholder="e.g. Panadol 500mg"/></label><label>Phone number<input placeholder="03xx xxxxxxx"/></label><label>Notes<textarea placeholder="Quantity, strength or anything else..."></textarea></label><label className="upload"><Upload/><span>Attach prescription (optional)<small>PDF, JPG or PNG</small></span><input type="file"/></label><button className="primary full" onClick={()=>setSent(true)}>Send request <ArrowUpRight/></button></>:<div className="success"><div className="successIcon"><Check/></div><h2>Request received.</h2><p>Thanks — in a production setup this would now be routed to the pharmacy team.</p><button className="secondary" onClick={close}>Close</button></div>}</div></div>}
 </div>
}
function LockIcon(){return <ShieldCheck/>}
createRoot(document.getElementById('root')).render(<App/>);
